### ISSUE TITLE
Not working without `sudo`

### ISSUE THREAD

**Issue by sounix000** [pojntfx/xeus-cling-binaries#2]
Thanks for the binaries - it's really wonderful to be able to use `xeus-cling` with using `conda`.

I fam using Fedora 33 and faced issues executing the commands given in the README. The solution was `sudo`-ing:

```bash

# Fetch the xeus-cling binary package for your architecture (x86_64 and aarch64 are supported)
curl -L -o /tmp/xeus-cling.tar.gz https://github.com/pojntfx/xeus-cling-binaries/releases/download/latest/xeus-cling.$(uname -m).tar.gz

# Extract the package to /usr/local/xeus-cling. You must install in this prefix.
XEUS_PREFIX=/usr/local/xeus-cling
sudo --stdin mkdir -p ${XEUS_PREFIX} # Enter sudo password
sudo tar -C ${XEUS_PREFIX} -xzf /tmp/xeus-cling.tar.gz

# Install the kernels
sudo jupyter kernelspec install ${XEUS_PREFIX}/share/jupyter/kernels/xcpp11 --sys-prefix
sudo jupyter kernelspec install ${XEUS_PREFIX}/share/jupyter/kernels/xcpp14 --sys-prefix
sudo jupyter kernelspec install ${XEUS_PREFIX}/share/jupyter/kernels/xcpp17 --sys-prefix

```

If you agree on the problem and the solution, please update the instructions in the README.

**Comment by pojntfx** [comment]
@sounix000 Sorry for not getting back to you earlier - glad to here the repo is helpful to you! I'm using Fedora (34) to and could reproduce the error; it seems as though I've basically copy-pasted the instructions from another project of mine (https://github.com/pojntfx/pojde/blob/main/modules/lang.ccpp.sh#L3-L29) and forgot to add the `sudo` prefixes where required. Fixed in https://github.com/pojntfx/xeus-cling-binaries/commit/d01e2af1923b1bee157b0b2dc7fe0e9f4937b5d8.

**Comment by pojntfx** [comment]
Backported to `pojntfx/xeus-sql-binaries` in https://github.com/pojntfx/xeus-sql-binaries/commit/e5a044e52e68b8f49ea1dadad2c428cca1711e67.
